---
- name: IMAGE PUSH
  hosts: localhost
  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: |
        cd /opt/docker
        docker build -t ${dockerhub_user}/${JOB_NAME} .
    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |        
        docker login -u {{ dockerhub_user }} -p {{ dockerhub_pass }}
        docker push ${dockerhub_user}/${JOB_NAME}
    - name: REMOVE OLD IMAGES FROM SERVER
      shell: docker rmi -f $(docker images ${dockerhub_user}/${JOB_NAME } -a -q) 

    - name: LOGOUT DOCKERHUB
      shell: docker logout
